# \u5BF9\u8C611\u914D\u7F6E
object.1.image=images/image1.jpg
object.1.string1=KID.
object.1.numberString=\u8D75\u4E00

# \u5BF9\u8C612\u914D\u7F6E
object.2.image=images/image2.jpg
object.2.string1=901
object.2.numberString=\u94B1\u4E8C

# \u5BF9\u8C613\u914D\u7F6E
object.3.image=images/image3.jpg
object.3.string1=\u963F\u7476ayao
object.3.numberString=\u5B59\u4E09

# \u5BF9\u8C614\u914D\u7F6E
object.4.image=images/image4.jpg
object.4.string1=\u5E0C
object.4.numberString=\u674E\u56DB

# \u5BF9\u8C615\u914D\u7F6E
object.5.image=images/image5.jpg
object.5.string1=zz
object.5.numberString=\u5468\u4E94

# \u5BF9\u8C616\u914D\u7F6E
object.6.image=images/image6.jpg
object.6.string1=\u590F
object.6.numberString=\u5434\u516D

# \u5BF9\u8C617\u914D\u7F6E
object.7.image=images/image7.jpg
object.7.string1=\u4EE5\u5B89
object.7.numberString=\u90D1\u4E03

# \u5BF9\u8C618\u914D\u7F6E
object.8.image=images/image8.jpg
object.8.string1=SZE WAN
object.8.numberString=\u738B\u516B

# \u5BF9\u8C619\u914D\u7F6E
object.9.image=images/image9.jpg
object.9.string1=liberty
object.9.numberString=\u51AF\u4E5D

# \u5BF9\u8C6110\u914D\u7F6E
object.10.image=images/image10.jpg
object.10.string1=\u66A7\u6627\u3001\u5C0F\u767D
object.10.numberString=\u9648\u5341

# \u5BF9\u8C6111\u914D\u7F6E
object.11.image=images/image11.jpg
object.11.string1=ybc
object.11.numberString=\u891A\u4E00

# \u5BF9\u8C6112\u914D\u7F6E
object.12.image=images/image12.jpg
object.12.string1=jiang
object.12.numberString=\u536B\u4E8C

# \u5BF9\u8C6113\u914D\u7F6E
object.13.image=images/image13.jpg
object.13.string1=\u5C0F\u6728
object.13.numberString=\u848B\u4E09

# \u5BF9\u8C6114\u914D\u7F6E
object.14.image=images/image14.jpg
object.14.string1=\u6C88\u56DB
object.14.numberString=\u6C88\u56DB

# \u5BF9\u8C6115\u914D\u7F6E
object.15.image=images/image15.jpg
object.15.string1=\u6F88\u94ED
object.15.numberString=\u97E9\u4E94

# \u5BF9\u8C6116\u914D\u7F6E
object.16.image=images/image16.jpg
object.16.string1=Edmund
object.16.numberString=\u6768\u516D

# \u5BF9\u8C6117\u914D\u7F6E
object.17.image=images/image17.jpg
object.17.string1=\u6731\u4E03
object.17.numberString=\u6731\u4E03

# \u5BF9\u8C6118\u914D\u7F6E
object.18.image=images/image18.jpg
object.18.string1=\u60F3\u8981\u6362\u4E2A\u6635\u79F0\uD83E\uDD14
object.18.numberString=\u79E6\u516B

# \u5BF9\u8C6119\u914D\u7F6E
object.19.image=images/image19.jpg
object.19.string1=Kid
object.19.numberString=\u5C24\u4E5D

# \u5BF9\u8C6120\u914D\u7F6E
object.20.image=images/image20.jpg
object.20.string1=Sky Lee
object.20.numberString=\u8BB8\u5341

# \u5BF9\u8C6121\u914D\u7F6E
object.21.image=images/image21.jpg
object.21.string1=\u54FC
object.21.numberString=\u4F55\u4E00

# \u5BF9\u8C6122\u914D\u7F6E
object.22.image=images/image22.jpg
object.22.string1=\u66F0\u8FB0
object.22.numberString=\u5415\u4E8C

# \u5BF9\u8C6123\u914D\u7F6E
object.23.image=images/image23.jpg
object.23.string1=Night
object.23.numberString=\u65BD\u4E09

# \u5BF9\u8C6124\u914D\u7F6E
object.24.image=images/image24.jpg
object.24.string1=JINjin
object.24.numberString=\u5F20\u56DB

# \u5BF9\u8C6125\u914D\u7F6E
object.25.image=images/image25.jpg
object.25.string1=\u56DE\u5FC6\u7EC8\u4E8E\u662F\u68A6
object.25.numberString=\u5B54\u4E94

# \u5BF9\u8C6126\u914D\u7F6E
object.26.image=images/image26.jpg
object.26.string1=\u591C\u884C
object.26.numberString=\u66F9\u516D

# \u5BF9\u8C6127\u914D\u7F6E
object.27.image=images/image27.jpg
object.27.string1=kaze
object.27.numberString=\u4E25\u4E03

# \u5BF9\u8C6128\u914D\u7F6E
object.28.image=images/image28.jpg
object.28.string1=\u2661\u5353\u6708\u4E5D\u65E5\u2606
object.28.numberString=\u534E\u516B

# \u5BF9\u8C6129\u914D\u7F6E
object.29.image=images/image29.jpg
object.29.string1=\u6211\u4E0D\u662F\u61A8\u61A8
object.29.numberString=\u91D1\u4E5D

# \u5BF9\u8C6130\u914D\u7F6E
object.30.image=images/image30.jpg
object.30.string1=anonimato
object.30.numberString=\u9B4F\u5341

# \u5BF9\u8C6131\u914D\u7F6E
object.31.image=images/image31.jpg
object.31.string1=\u9676\u4E00
object.31.numberString=\u9676\u4E00

# \u5BF9\u8C6132\u914D\u7F6E
object.32.image=images/image32.jpg
object.32.string1="\u00C4ventyr"
object.32.numberString=\u59DC\u4E8C

# \u5BF9\u8C6133\u914D\u7F6E
object.33.image=images/image33.jpg
object.33.string1=\u4E0B\u4E00\u7AD9\u8239\u5C06\u9A76\u5411\u4F55\u65B9
object.33.numberString=\u621A\u4E09
